name: My first Workflow

#trigger
on:
- push

#jobs in the workflow
jobs:
#job name
  my-first-workflow:
    #os that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps: 
    - name: echo the date
      run: echo "the current time and date in Githun is $(date)"
    - name: echo information about the text
      run: echo "head_ref - ${{github.head_ref}}, owner - ${{github.respository_owner }}"
    - name: List runner name
      run: echo "runner os - {{ runner.os }}"
    - name: Echo my secret
      run: echo "MY_SECRET is ${{secret.MY_SECRET}}"
    - name: List my current directory
      run: ls - l
    - name: Checkout the current repo
      uses: actions/checkout@v3
    - name: List my current directory after checkout
      run: ls - l 