name: Release and deploy Todo

on:
  push
    branches:
    - "release/.+"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Check out the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}